services:
  front: 
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./frontend/index.html:/app/index.html
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/vite.config.ts:/app/vite.config.ts

  back:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/src 
      # - ./backend/database:/app/database plus nécessaire car on ne passe plus par sqlite mais par postgres

  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mdpsecret
      POSTGRES_USER: thegoodcorner
      POSTGRES_DB: thegoodcorner
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
